server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Esta línea es la magia de las SPA: si no encuentra el archivo, redirige al index.html
        try_files $uri $uri/ /index.html;
    }
}